# This file was changed - most of the content was not needed.
## File generated by the BNF Converter (bnfc 2.9.4.1).

# Makefile for building the parser and test program.

GHC        = ghc
GHC_OPTS   = -o interpreter
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

BNFC  = /home/students/inf/PUBLIC/MRJP/bin/bnfc
# BNFC  = /Users/michalrembalski/.local/bin/bnfc

# List of goals not corresponding to file names.

.PHONY : all clean

# Default goal.

all : Main

# Rules for building the parser.
Ruskell/Abs.hs Ruskell/LexRuskell.x Ruskell/ParRuskell.y Ruskell/Print.hs Ruskell/Test.hs : Ruskell.cf
	${BNFC} --haskell -d --functor Ruskell.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Main : Ruskell/Abs.hs Ruskell/Lex.hs Ruskell/Par.hs Ruskell/Print.hs Ruskell/Test.hs Interpreter.hs Main.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.
clean :
	rm -rf Ruskell
	rm -rf *.hi *.o interpreter

# EOF
